In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = tf.Variable(3.0, name='x')

In [4]:
x.numpy()

3.0

In [5]:
with tf.GradientTape() as tape:
  y = x ** 2

In [6]:
y.numpy()

9.0

In [7]:
grad_dy_dx = tape.gradient(y, x)

In [10]:
tape.gradient(y, x)

RuntimeError: ignored

In [23]:
x1 = tf.Variable(3.0, name='x1')
x2 = tf.Variable(5.0, name='x2') + 5

In [24]:
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x2)
  y1 = x1 ** 2 + x1 * x2 + x2 ** 3 +5
  y2 = x1 * x2

In [25]:
grads = tape.gradient(y1, [x1, x2])

In [26]:
grads

[<tf.Tensor: shape=(), dtype=float32, numpy=16.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=303.0>]

In [27]:
X = np.random.randn(100, 5)
W = np.random.uniform(size=(5, 1))
b = np.random.uniform(size=(1,))
Y = X @ W + b

In [28]:
Y.shape

(100, 1)

In [32]:
W_opt = tf.Variable(np.random.randn(5, 1), name='W_opt')
b_opt = tf.Variable(np.random.randn(1), name='b_opt')
X_tensor = tf.convert_to_tensor(X)
Y_tensor = tf.convert_to_tensor(Y)

In [33]:
with tf.GradientTape() as tape:
  Y_pred = X_tensor @ W_opt + b_opt
  loss = tf.math.reduce_mean((Y_pred - Y_tensor) ** 2)

In [34]:
grads = tape.gradient(loss, [W_opt, b_opt])

In [35]:
grads

[<tf.Tensor: shape=(5, 1), dtype=float64, numpy=
 array([[ 3.6762943 ],
        [-3.19679906],
        [ 1.15691   ],
        [-1.49570636],
        [ 0.97979199]])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([-2.48020475])>]

In [36]:
from tensorflow.keras.models import Model

In [39]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, activation='sigmoid'))
model.add(tf.keras.layers.Dense(5, activation='relu'))
model.add(tf.keras.layers.Dense(1))
model.add_loss(tf.keras.losses.MSE)

In [46]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1))

In [47]:
adam = tf.keras.optimizers.Adam()
model.compile(optimizer=adam, loss=tf.keras.losses.MSE)

In [ ]:
model.fit(X, Y, batch_size=5, epochs=100)

In [52]:
model.weights

[<tf.Variable 'dense_7/kernel:0' shape=(5, 1) dtype=float32, numpy=
 array([[0.4441787 ],
        [0.5549061 ],
        [0.42785734],
        [0.58080965],
        [0.42778632]], dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(1,) dtype=float32, numpy=array([0.8856815], dtype=float32)>]

In [53]:
W

array([[0.50775586],
       [0.74344419],
       [0.59611087],
       [0.5993095 ],
       [0.73721658]])

In [54]:
b

array([0.98478827])

In [57]:
x = tf.keras.layers.Input(shape=5)
layer = tf.keras.layers.Dense(5, activation='relu')
y4 = layer(x)
y5 = layer(x)
y1 = tf.keras.layers.Dense(10, activation='sigmoid')(x)
y2 = tf.keras.layers.Dense(10)(x)
y = y1 + y2 ** 2
y3 = tf.keras.layers.Dense(1, activation='relu')(y1)
model = Model(inputs=x, outputs=y)